version: '3.8'
services:
  meble-backend:
    build:
      context: ./Meble.Server
      dockerfile: Dockerfile
    ports:
      - "8442:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pysiec123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    volumes:
      - ./Meble.Server:/app
      - ./Meble.Server/aspnetapp.pfx:/app/aspnetapp.pfx

  meble-client:
    build:
      context: ./meble.client
      dockerfile: Dockerfile
    ports:
      - "8444:443"
    volumes:
      - ./meble.client/nginx.conf:/etc/nginx/nginx.conf
      - ./Meble.Server/aspnetapp.crt:/etc/ssl/certs/aspnetapp.crt
      - ./Meble.Server/aspnetapp.key:/etc/ssl/private/aspnetapp.key
